-- Communities Table
CREATE TABLE IF NOT EXISTS communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Community Schedules Table
CREATE TABLE IF NOT EXISTS community_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT REFERENCES communities(id) ON DELETE CASCADE NOT NULL,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
    time TEXT NOT NULL, -- HH:MM format
    type TEXT NOT NULL CHECK (type IN ('Missa', 'Celebração')),
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_schedules ENABLE ROW LEVEL SECURITY;

-- Policies for Communities
CREATE POLICY "Public Read Communities" ON communities 
    FOR SELECT USING (true);

CREATE POLICY "Admin Insert Communities" ON communities 
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin Update Communities" ON communities 
    FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Admin Delete Communities" ON communities 
    FOR DELETE TO authenticated USING (true);

-- Policies for Community Schedules
CREATE POLICY "Public Read Community Schedules" ON community_schedules 
    FOR SELECT USING (true);

CREATE POLICY "Admin Insert Community Schedules" ON community_schedules 
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin Update Community Schedules" ON community_schedules 
    FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Admin Delete Community Schedules" ON community_schedules 
    FOR DELETE TO authenticated USING (true);
