-- Fix Banners Table
CREATE TABLE IF NOT EXISTS public.banners (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    image_url text not null,
    link text,
    desktop_order integer default 0,
    mobile_order integer default 0,
    active boolean default true
);

-- Enable RLS for valid operations
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any to avoid conflicts (be careful)
DROP POLICY IF EXISTS "Public Read Banners" ON public.banners;
DROP POLICY IF EXISTS "Admin Insert Banners" ON public.banners;
DROP POLICY IF EXISTS "Admin Update Banners" ON public.banners;
DROP POLICY IF EXISTS "Admin Delete Banners" ON public.banners;

-- Re-create policies
CREATE POLICY "Public Read Banners" ON public.banners FOR SELECT USING (true);
CREATE POLICY "Admin Insert Banners" ON public.banners FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admin Update Banners" ON public.banners FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admin Delete Banners" ON public.banners FOR DELETE TO authenticated USING (true);


-- Fix News Table Permissions just in case
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read News" ON public.news;
DROP POLICY IF EXISTS "Admin Insert News" ON public.news;
DROP POLICY IF EXISTS "Admin Update News" ON public.news;
DROP POLICY IF EXISTS "Admin Delete News" ON public.news;

CREATE POLICY "Public Read News" ON public.news FOR SELECT USING (true);
CREATE POLICY "Admin Insert News" ON public.news FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admin Update News" ON public.news FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admin Delete News" ON public.news FOR DELETE TO authenticated USING (true);

-- Fix Notices Table Permissions
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Notices" ON public.notices;
DROP POLICY IF EXISTS "Admin Insert Notices" ON public.notices;
DROP POLICY IF EXISTS "Admin Update Notices" ON public.notices;
DROP POLICY IF EXISTS "Admin Delete Notices" ON public.notices;

CREATE POLICY "Public Read Notices" ON public.notices FOR SELECT USING (true);
CREATE POLICY "Admin Insert Notices" ON public.notices FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admin Update Notices" ON public.notices FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admin Delete Notices" ON public.notices FOR DELETE TO authenticated USING (true);
