-- Create forms table
CREATE TABLE IF NOT EXISTS forms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    submit_label TEXT DEFAULT 'Enviar',
    success_message TEXT DEFAULT 'Formulário enviado com sucesso!',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create form_fields table
CREATE TABLE IF NOT EXISTS form_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT REFERENCES forms(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    field_name TEXT NOT NULL, -- key for json storage
    field_type TEXT NOT NULL, -- text, email, tel, textarea, select, date
    placeholder TEXT,
    required BOOLEAN DEFAULT false,
    options TEXT[], -- Array of strings for select options
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_forms_slug ON forms(slug);
CREATE INDEX IF NOT EXISTS idx_form_fields_form_id ON form_fields(form_id);

-- Seed Initial Data for Baptism (Batismo)
INSERT INTO forms (title, slug, description, submit_label, success_message)
VALUES (
    'Solicitação de Batismo', 
    'batismo', 
    'O Batismo é a porta de entrada para a vida cristã. Preencha o formulário abaixo para dar início ao processo.', 
    'Solicitar Batismo', 
    'Sua solicitação foi enviada! A secretaria entrará em contato para os próximos passos.'
) ON CONFLICT (slug) DO NOTHING;

-- Get the ID of the inserted/existing form
DO $$
DECLARE
    v_form_id BIGINT;
BEGIN
    SELECT id INTO v_form_id FROM forms WHERE slug = 'batismo';

    -- Insert fields if form exists (simple idempotent check by deleting existing fields for this form first to avoid easy dupes during dev)
    -- WARNING: In production be careful, but for dev this ensures fresh seed
    DELETE FROM form_fields WHERE form_id = v_form_id;

    INSERT INTO form_fields (form_id, label, field_name, field_type, placeholder, required, options, order_index)
    VALUES
    (v_form_id, 'Nome da Criança', 'child_name', 'text', 'Nome completo', true, null, 1),
    (v_form_id, 'Idade da Criança', 'child_age', 'text', 'Ex: 3 meses', true, null, 2),
    (v_form_id, 'Nome do Pai', 'father_name', 'text', 'Nome completo', true, null, 3),
    (v_form_id, 'Nome da Mãe', 'mother_name', 'text', 'Nome completo', true, null, 4),
    (v_form_id, 'Pais são casados na Igreja Católica?', 'catholic_marriage', 'select', null, true, ARRAY['Sim', 'Não'], 5),
    (v_form_id, 'Telefone / WhatsApp', 'phone', 'tel', '(00) 00000-0000', true, null, 6),
    (v_form_id, 'Bairro de Residência', 'neighborhood', 'text', '', true, null, 7),
    (v_form_id, 'Observações Adicionais', 'message', 'textarea', '', false, null, 8);
END $$;
