create table if not exists public.galleries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  event_date date,
  cover_image text,
  description text
);

create table if not exists public.gallery_images (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  gallery_id bigint not null references public.galleries(id) on delete cascade,
  image_url text not null,
  display_order integer default 0
);

create index if not exists idx_gallery_images_gallery_id
  on public.gallery_images (gallery_id);

create index if not exists idx_gallery_images_gallery_order
  on public.gallery_images (gallery_id, display_order);

alter table public.galleries enable row level security;
alter table public.gallery_images enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'galleries'
      and policyname = 'Public Read Galleries'
  ) then
    create policy "Public Read Galleries"
      on public.galleries
      for select
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'galleries'
      and policyname = 'Admin Insert Galleries'
  ) then
    create policy "Admin Insert Galleries"
      on public.galleries
      for insert
      to authenticated
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'galleries'
      and policyname = 'Admin Update Galleries'
  ) then
    create policy "Admin Update Galleries"
      on public.galleries
      for update
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'galleries'
      and policyname = 'Admin Delete Galleries'
  ) then
    create policy "Admin Delete Galleries"
      on public.galleries
      for delete
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'gallery_images'
      and policyname = 'Public Read Gallery Images'
  ) then
    create policy "Public Read Gallery Images"
      on public.gallery_images
      for select
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'gallery_images'
      and policyname = 'Admin Insert Gallery Images'
  ) then
    create policy "Admin Insert Gallery Images"
      on public.gallery_images
      for insert
      to authenticated
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'gallery_images'
      and policyname = 'Admin Update Gallery Images'
  ) then
    create policy "Admin Update Gallery Images"
      on public.gallery_images
      for update
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'gallery_images'
      and policyname = 'Admin Delete Gallery Images'
  ) then
    create policy "Admin Delete Gallery Images"
      on public.gallery_images
      for delete
      to authenticated
      using (true);
  end if;
end
$$;

notify pgrst, 'reload schema';
