-- Create a table to track keep-alive pings
create table if not exists keep_alive (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (optional, but good practice)
alter table keep_alive enable row level security;

-- Allow anonymous inserts (since our script might run as anon or service role)
-- Ideally, we use service_role key for the script, which bypasses RLS.
-- But if we want to be safe:
create policy "Allow inserts for service role"
on keep_alive
for insert
to service_role
with check (true);

create policy "Allow reads for service role"
on keep_alive
for select
to service_role
using (true);
