-- Create pastoral_members table
create table public.pastoral_members (
  id bigint generated by default as identity primary key,
  pastoral_id bigint references public.pastorals(id) on delete cascade not null,
  name text not null,
  role text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
