-- Create Banners Table
create table public.banners (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  image_url text not null,
  link text,
  desktop_order integer default 0,
  mobile_order integer default 0,
  active boolean default true
);

-- Create Galleries Table
create table public.galleries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  event_date date,
  cover_image text,
  description text
);

-- Create Gallery Images Table
create table public.gallery_images (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  gallery_id bigint references public.galleries(id) on delete cascade not null,
  image_url text not null,
  display_order integer default 0
);

-- Create Pages Table (for institutional content)
create table public.pages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  slug text not null unique, -- e.g. 'a-paroquia', 'sacramentos', 'contato'
  title text not null,
  content text, -- HTML or Markdown content
  meta_description text
);

-- Enable RLS
alter table public.banners enable row level security;
alter table public.galleries enable row level security;
alter table public.gallery_images enable row level security;
alter table public.pages enable row level security;

-- Policies (Public Read, Admin Write)
create policy "Public Read Banners" on public.banners for select using (true);
create policy "Admin Insert Banners" on public.banners for insert to authenticated with check (true);
create policy "Admin Update Banners" on public.banners for update to authenticated using (true);
create policy "Admin Delete Banners" on public.banners for delete to authenticated using (true);

create policy "Public Read Galleries" on public.galleries for select using (true);
create policy "Admin Insert Galleries" on public.galleries for insert to authenticated with check (true);
create policy "Admin Update Galleries" on public.galleries for update to authenticated using (true);
create policy "Admin Delete Galleries" on public.galleries for delete to authenticated using (true);

create policy "Public Read Gallery Images" on public.gallery_images for select using (true);
create policy "Admin Insert Gallery Images" on public.gallery_images for insert to authenticated with check (true);
create policy "Admin Update Gallery Images" on public.gallery_images for update to authenticated using (true);
create policy "Admin Delete Gallery Images" on public.gallery_images for delete to authenticated using (true);

create policy "Public Read Pages" on public.pages for select using (true);
create policy "Admin Insert Pages" on public.pages for insert to authenticated with check (true);
create policy "Admin Update Pages" on public.pages for update to authenticated using (true);
create policy "Admin Delete Pages" on public.pages for delete to authenticated using (true);
