
-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- News Table
create table public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  image_url text,
  published boolean default true
);

-- Events Table
create table public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  event_date timestamp with time zone not null,
  location text,
  image_url text
);

-- Schedules Table (Mass times)
create table public.schedules (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  day_of_week text not null, -- 'Segunda', 'Terça', etc.
  time time not null,
  description text, -- 'Missa', 'Adoração', 'Secretaria'
  type text -- 'missa', 'secretaria', 'confissao'
);

-- Pastorals Table
create table public.pastorals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  coordinator text,
  contact text,
  image_url text
);

-- Notices Table (Avisos Importantes)
create table public.notices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  message text not null,
  is_urgent boolean default false,
  expires_at timestamp with time zone
);

-- Reform Updates Table
create table public.reform_updates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  image_url text,
  percent_complete integer default 0,
  stage text -- 'Fundação', 'Alvenaria', 'Acabamento', etc.
);

-- Form Submissions Table (Webhooks also send here if needed, or just keep log)
create table public.form_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  form_type text not null, -- 'batismo', 'catequese', etc.
  data jsonb not null,
  status text default 'new' -- 'new', 'read', 'archived'
);

-- Enable RLS on all tables
alter table public.news enable row level security;
alter table public.events enable row level security;
alter table public.schedules enable row level security;
alter table public.pastorals enable row level security;
alter table public.notices enable row level security;
alter table public.reform_updates enable row level security;
alter table public.form_submissions enable row level security;

-- Policies (Public Read, Admin Write)
-- Example:
create policy "Public Read" on public.news for select using (true);
create policy "Admin Insert" on public.news for insert to authenticated with check (true);
create policy "Admin Update" on public.news for update to authenticated using (true);
create policy "Admin Delete" on public.news for delete to authenticated using (true);
-- You would need to add similar policies for all tables.
