-- Community Coordinators Table
CREATE TABLE IF NOT EXISTS community_coordinators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT REFERENCES communities(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    contact TEXT,
    role TEXT DEFAULT 'Coordenador',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE community_coordinators ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public Read Community Coordinators" ON community_coordinators 
    FOR SELECT USING (true);

CREATE POLICY "Admin Insert Community Coordinators" ON community_coordinators 
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin Update Community Coordinators" ON community_coordinators 
    FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Admin Delete Community Coordinators" ON community_coordinators 
    FOR DELETE TO authenticated USING (true);
