-- RUN THIS IN YOUR SUPABASE SQL EDITOR TO FIX SAVING ISSUES

-- 1. Create pastoral_members table (if it doesn't exist)
create table if not exists public.pastoral_members (
  id bigint generated by default as identity primary key,
  pastoral_id bigint references public.pastorals(id) on delete cascade not null,
  name text not null,
  role text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add image_url to notices (if it doesn't exist)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'notices' and column_name = 'image_url') then
    alter table public.notices add column image_url text;
  end if;
end $$;

-- 3. Add image_url to pastorals (if it doesn't exist)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'pastorals' and column_name = 'image_url') then
    alter table public.pastorals add column image_url text;
  end if;
end $$;

-- 4. Enable RLS (Security) for pastoral_members
alter table public.pastoral_members enable row level security;

-- 5. Create policies for pastoral_members (public read, anon insert for now to matched others, or aligned to existing policies)
create policy "Allow public read access"
  on public.pastoral_members for select
  using (true);

create policy "Allow insert for anon (demo)"
  on public.pastoral_members for insert
  with check (true);

create policy "Allow update for anon (demo)"
  on public.pastoral_members for update
  using (true);

create policy "Allow delete for anon (demo)"
  on public.pastoral_members for delete
  using (true);
